apiVersion: v1
kind: Namespace
metadata:
  name: claude-coordination
  labels:
    name: claude-coordination
    app.kubernetes.io/name: claude-coordination
    app.kubernetes.io/part-of: claude-coordination-platform
    environment: production
    version: v3.0.0
  annotations:
    description: "Claude Code Coordination Enterprise Platform Namespace"
    owner: "Claude Code Coordination Team"
    contact: "admin@claude-coordination.ai"
---
apiVersion: v1
kind: Namespace
metadata:
  name: claude-coordination-monitoring
  labels:
    name: claude-coordination-monitoring
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: claude-coordination-platform
    environment: production
    version: v3.0.0
  annotations:
    description: "Monitoring namespace for Claude Code Coordination"
    owner: "Claude Code Coordination Team"
---
# Network Policy for enhanced security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: claude-coordination-network-policy
  namespace: claude-coordination
spec:
  podSelector:
    matchLabels:
      app: claude-coordination
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: claude-coordination-monitoring
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: database
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - namespaceSelector:
        matchLabels:
          name: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80