apiVersion: v1
kind: Secret
metadata:
  name: claude-coordination-secrets
  namespace: claude-coordination
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_REPLICATION_PASSWORD: "${POSTGRES_REPLICATION_PASSWORD}"
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
  JWT_SECRET: "${JWT_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: claude-coordination-monitoring
type: Opaque
stringData:
  admin-user: "${GRAFANA_USER}"
  admin-password: "${GRAFANA_PASSWORD}"
---
# TLS Certificate Secret (placeholder - use cert-manager in production)
apiVersion: v1
kind: Secret
metadata:
  name: claude-coordination-tls
  namespace: claude-coordination
type: kubernetes.io/tls
data:
  tls.crt: # Base64 encoded certificate
  tls.key: # Base64 encoded private key